apiVersion: apps/v1

kind: Deployment

metadata:
  name: springboot-k8s-demo
<<<<<<< HEAD
  namespace: jenkins
=======
  namespace: jenkinsnew
>>>>>>> 727409b2a408a15f6bb5dc2aff31583e0e81a335

spec:

  replicas: 3

  selector:
    matchLabels:
      app: springboot-k8s-demo

  template:

    metadata:
      labels:
        app: springboot-k8s-demo

    spec:

      containers:

        - name: springboot-k8s-demo

          image: myspring:1.0

          imagePullPolicy: IfNotPresent

          ports:
<<<<<<< HEAD
            - containerPort: 8080
=======
            - containerPort: 8080
>>>>>>> 727409b2a408a15f6bb5dc2aff31583e0e81a335
