apiVersion: v1

kind: Service

metadata:
  name: springboot-service
  namespace: jenkins

spec:

  type: LoadBalancer

  selector:
    app: springboot-k8s-demo

  ports:

    - protocol: TCP
      port: 8080
      targetPort: 8080